// tslint:disable
/**
 * Stable - Auth Service
 * An authentication service API for Stable
 *
 * The version of the OpenAPI document: 0.0.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface AcceptedResponseDto
 */
export interface AcceptedResponseDto {
    /**
     * An informational message
     * @type {string}
     * @memberof AcceptedResponseDto
     */
    message: string;
}
